[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x696969"
blue = "0x007FFF"
cyan = "0x00CCCC"
green = "0x03C03C"
magenta = "0xFF1493"
red = "0xFF2400"
white = "0xFFFAFA"
yellow = "0xFDFF00"

[colors.normal]
black = "0x10100E"
blue = "0x0087BD"
cyan = "0x20B2AA"
green = "0x009F6B"
magenta = "0x9A4EAE"
red = "0xC40233"
white = "0xC6C6C4"
yellow = "0xFFD700"

[colors.primary]
background = "0x10100E"
foreground = "0xC6C6C4"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "InconsolataLGC Nerd Font"
style = "Regular"

[font.bold_italic]
family = "WenQuanYi Micro Hei Mono"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "InconsolataLGC Nerd Font"
style = "Regular"

[font.normal]
family = "InconsolataLGC Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
decorations_theme_variant = "Dark"
opacity = 0.7
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 12
y = 12

[window.position]
x = 0
y = 0
