#!/usr/bin/bash

if [[ "$1" == "tp" ]]; then
	# playerctl -p $(cat ~/.config/playerctl-priority-list | tr '\n' ',') play-pause
  playerctl play-pause
elif [[ "$1" == "n" ]]; then
  # playerctl -p $(cat ~/.config/playerctl-priority-list | tr '\n' ',') next
  playerctl next
elif [[ "$1" == "p" ]]; then
  # playerctl -p $(cat ~/.config/playerctl-priority-list | tr '\n' ',') previous
  playerctl previous
elif [[ "$1" == "s" ]]; then
  # playerctl -p $(cat ~/.config/playerctl-priority-list | tr '\n' ',') stop
  playerctl stop
fi
